name: CI

#on:
#  push:
#    branches: [ main ]


on:
  release:
    types: [ created ]

jobs:
  build_skia:
    name: build skia on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019 ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: pip install
        run: python -m pip install --no-cache-dir --upgrade patch

      - name: build
        run: python scripts/build.py

      - name: archive
        run: python scripts/archive.py

      - uses: actions/upload-artifact@v2
        with:
          name: skia_windows_release_x64.zip
          path: '*.zip'
